export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: 'caregory/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'caregory/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'caregory/FETCH_CATEGORIES_FAILED',
};
